// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH7EeMY5A8GptMCRyeAsqfcZGfU75GaMI',
    appId: '1:1030539693888:web:b3642df023c441330cf4a5',
    messagingSenderId: '1030539693888',
    projectId: 'staff-cleaner',
    authDomain: 'staff-cleaner.firebaseapp.com',
    storageBucket: 'staff-cleaner.appspot.com',
    measurementId: 'G-DQGCYJ92BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HXy9M7i4GYvEOseV5vWnViNZSzq44V0',
    appId: '1:1030539693888:android:41a36b474013150e0cf4a5',
    messagingSenderId: '1030539693888',
    projectId: 'staff-cleaner',
    storageBucket: 'staff-cleaner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQBzAmRn8kaINQu3wXkigs3ygsyEKDItI',
    appId: '1:1030539693888:ios:26cb7ee933e5a8880cf4a5',
    messagingSenderId: '1030539693888',
    projectId: 'staff-cleaner',
    storageBucket: 'staff-cleaner.appspot.com',
    iosClientId: '1030539693888-49f2fdd98biemrev8n5abnu7dsvd2o4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffCleaner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQBzAmRn8kaINQu3wXkigs3ygsyEKDItI',
    appId: '1:1030539693888:ios:26cb7ee933e5a8880cf4a5',
    messagingSenderId: '1030539693888',
    projectId: 'staff-cleaner',
    storageBucket: 'staff-cleaner.appspot.com',
    iosClientId: '1030539693888-49f2fdd98biemrev8n5abnu7dsvd2o4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffCleaner',
  );
}
